objects/Account.object
<CustomObject>
    <fields>
        <fullName>Star_Rating_Review_ID__c</fullName>
        <label>Star Rating Review ID</label>
        <referenceTo>Star_Rating_Review__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Star_Rating_Structure_Type__c</fullName>
        <description>Lookup to Structure Type for Property</description>
        <label>Star Rating Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Star Ratings Review (Structure Types)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Star_Rating_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Star_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_complete__c</fullName>
        <label>Review completed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Structure_Type__c</fullName>
        <label>Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Star Rating Reviews</relationshipLabel>
        <relationshipName>Star_Rating_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Star Rating Review</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Star Ratings Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Star Rating Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Structure_Type__c.object
<CustomObject>
    <description>The structure types that a property can be classified as.</description>
    <label>Structure Type</label>
    <nameField>
        <label>Structure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Structure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StarRatingReviewClass_Test.cls
@isTest
private class StarRatingReviewClass_Test {

  static testMethod void myUnitTest() {    
  
    Account testAccount = new Account (Name = 'TestAccount');
    insert testAccount;
   
    Structure_Type__c testStructure = new Structure_Type__c (Name = 'TestStructure');
    insert testStructure;
    
    test.startTest();
    StarRatingReviewClass objStarRating = new StarRatingReviewClass();
    List<Star_Rating_Review__c> newStarRatings = new List<Star_Rating_Review__c>();
    
    Star_Rating_Review__c testStarRating = new Star_Rating_Review__c (Account__c  = testAccount.Id
                                                                     ,Structure_Type__c = testStructure.Id
                                                                     ,Review_Complete__c = 'Yes');        
    insert testStarRating;
    
    newStarRatings.add(testStarRating);
    objStarRating.syncAccountStarRatings(newStarRatings); 
        
    //Query the Database to get the updated lookup fields
    Account myTestAccount = [SELECT Id
                                    ,Star_Rating_Structure_Type__c
                                    ,Star_Rating_Review_ID__c 
                               FROM Account 
                              WHERE Id = :testAccount.Id]; 
                                
    system.assertEquals(myTestAccount.Star_Rating_Structure_Type__c, testStructure.Id);
    system.assertEquals(myTestAccount.Star_Rating_Review_ID__c, testStarRating.Id);
    
    Star_Rating_Review__c newerStarRating = new Star_Rating_Review__c (Account__c  = testAccount.Id
                                                                      ,Structure_Type__c = testStructure.Id
                                                                      ,Review_Complete__c = 'Yes');        
    insert newerStarRating;
    objStarRating.syncAccountStarRatings(newStarRatings);
    
    //Query the Database to get the updated lookup fields
    Account updatedTestAccount = [SELECT Id
                                         ,Star_Rating_Structure_Type__c
                                         ,Star_Rating_Review_ID__c 
                                    FROM Account 
                                   WHERE Id = :testAccount.Id]; 
                                     
    system.assertEquals(updatedTestAccount.Star_Rating_Structure_Type__c, testStructure.Id);
    system.assertEquals(updatedTestAccount.Star_Rating_Review_ID__c, newerStarRating.Id);
    
    test.stopTest();    
  }
}