objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Manager_Email__c</fullName>
        <description>Email address for Market Manager (Account Owner from PSG Salesforce)</description>
        <inlineHelpText>Email address for Market Manager</inlineHelpText>
        <label>Market Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Market_Manager_Name__c</fullName>
        <description>Name for Market Manager (Account Owner) from PSG Salesforce</description>
        <inlineHelpText>This is the Account Owner from PSG Salesforce</inlineHelpText>
        <label>Market Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Account_Repco__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Repcos</relationshipLabel>
        <relationshipName>Account_Repcos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Repco</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Repco</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Repcos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account_Repco__c</fullName>
        <label>Account Repco</label>
        <referenceTo>Account_Repco__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Go_Date__c</fullName>
        <label>Go Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Connection_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Integration Connection Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PSG_Account_ID__c</fullName>
        <description>Used to build out the Connection Integration Key in before insert trigger. This formula field allows us to save a SOQL query to get the account object&apos;s data</description>
        <formula>Account__r.External_Account_Id__c</formula>
        <label>PSG Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <picklist>
            <picklistValues>
                <fullName>EQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Displays the highest rollout step. Can be manually overridden.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Connecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Confirmation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Connectivity_System__c.object
<CustomObject>
    <fields>
        <fullName>Connectivity_System_Type__c</fullName>
        <label>Connectivity System Type</label>
        <picklist>
            <picklistValues>
                <fullName>CRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Allocator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Connectivity_Vendor__c</fullName>
        <label>Connectivity Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectivity Systems</relationshipLabel>
        <relationshipName>Connectivity_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Go_Date__c</fullName>
        <label>Go Date</label>
        <type>Date</type>
    </fields>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConnectionClass.cls
public with sharing class ConnectionClass {
    
    public void buildConnectionIntegrationKeys(List<Connection__c> myConnections){
        String concatenator = ':'; //hasta la vista, baby
        for (Connection__c myConnection : myConnections){
        		if (myConnection.Status__c == 'Disconnected'){
        			myConnection.Integration_Connection_Key__c = null;
        		}
        		if (myConnection.Status__c == 'Connected'){
                	myConnection.Integration_Connection_Key__c =  myConnection.PSG_Account_ID__c + concatenator
                    	                                        + myConnection.Type__c + concatenator
                        	                                    + myConnection.Platform__c;
        		}
        }       
    }
    
    public static Connection__c getConnection(Id connectionId){
        Connection__c myConnection = [SELECT Id
                                            ,Name
                                            ,Account__c
                                            ,Account__r.Name
                                            ,Account__r.Id
                                            ,Type__c
                                            ,Status__c
                                            ,Platform__c
                                            ,Go_Date__c
                                            ,LastModifiedDate
                                            ,Connectivity_System__c
                                            ,Connectivity_System__r.Connectivity_System_Type__c 
                                            ,Account_Repco__c
                                            ,Account__r.Market_Manager_Email__c
                                            ,Account__r.Market_Manager_Name__c
                                            ,Connectivity_System__r.Connectivity_Vendor__c
                                            ,Connectivity_System__r.Connectivity_Vendor__r.Market_Manager_Email__c // Added Steve 10/6
                                            ,Connectivity_System__r.Connectivity_Vendor__r.Market_Manager_Name__c //Added Steve 10/6
                                       FROM Connection__c
                                      WHERE Id = :connectionId];
        return myConnection;
    }
    
    public static List<Connection__c> getConnectionsByAccountId (Id accountId){
        return [SELECT  Id
                       ,Name 
                       ,Connectivity_System__c
                       ,Connectivity_System__r.Connectivity_Vendor__r.Name
                       ,Connectivity_System__r.Connectivity_System_Type__c
                       ,Type__c
                       ,Status__c
                       ,Platform__c
                       ,Go_Date__c
                       ,LastModifiedDate
                       ,LastModifiedBy.FirstName
                       ,LastModifiedBy.LastName 
                FROM  Connection__c 
               WHERE  Account__c = :accountId
            ORDER BY  LastModifiedDate DESC];
    }
    
    
    // Check for updates before upserting. Since this is displayed with rollout steps, and notes, 
    public static void upsertConnection(Connection__c myConnection){
    	if (myConnection.Id != null){
    		Connection__c oldConnection = getConnection(myConnection.Id);
    		if (oldConnection != myConnection) upsert myConnection;
    	} else{
    		insert myConnection;
    	}
    }
}