objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Represents a hotel or property on an Expedia Inc point of sale</description>
        <label>Hotel</label>
    </recordTypes>
</CustomObject>

objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Connectivity_System__c.object
<CustomObject>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailWidgetWrapper_Test.cls
@isTest
private class EmailWidgetWrapper_Test {

    static testMethod void myUnitTest() {
    	string FROM_ADDRESS = 'test@test.com';
    	Set<String> TEMPLATE_FOLDERS = new Set<String>{'Test Folder'};
		
		Case myCase = new Case(Origin = 'Web', Subject = 'Test Case', Status = 'Testing');
		insert myCase;
		
		Connectivity_System__c myConnectivitySystem = new Connectivity_System__c (Name = 'TestConnectivitySystem');
		insert myConnectivitySystem;
		
		Account myAccount = new Account(Name = 'Test Hotel');
		insert myAccount;
		
		Connection__c myConnection = new Connection__c(Connectivity_System__c = myConnectivitySystem.Id, Account__c = myAccount.Id);
		insert myConnection;    	
    	
        EmailWidgetWrapper emailWidget = new EmailWidgetWrapper(myConnection, myCase.Id, TEMPLATE_FOLDERS, FROM_ADDRESS);        
        emailWidget.sendConnectivityEmail();
    }
}