objects/Account.object
<CustomObject>
    <fields>
        <fullName>Star_Rating_Review_ID__c</fullName>
        <label>Star Rating Review ID</label>
        <referenceTo>Star_Rating_Review__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Star_Rating_Structure_Type__c</fullName>
        <description>Lookup to Structure Type for Property</description>
        <label>Star Rating Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Star Ratings Review (Structure Types)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Star_Rating_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Star_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_complete__c</fullName>
        <label>Review completed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Structure_Type__c</fullName>
        <label>Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Star Rating Reviews</relationshipLabel>
        <relationshipName>Star_Rating_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Star Rating Review</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Star Ratings Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Star Rating Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Structure_Type__c.object
<CustomObject>
    <description>The structure types that a property can be classified as.</description>
    <label>Structure Type</label>
    <nameField>
        <label>Structure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Structure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StarRatingReviewClass.cls
public with sharing class StarRatingReviewClass {

  // After Update, After Insert of Star Ratings update the lookup fields for
  // Structure Type & Star Rating Review on the Account
  
  // Currently could get data out of Sync if Star Rating Review's are ever deleted.
  // Users will not have the ability to delete Star Rating Reviews though
  public void syncAccountStarRatings(List<Star_Rating_Review__c> myStarRatingsReviews){
    // Loop through all reviews
    for (Star_Rating_Review__c review : myStarRatingsReviews) {
      // If review is complete we want to work with it
      if (review.Review_Complete__c == 'Yes') {
        accountIds.add(review.Account__c);
      }
    }
    
    // Make sure we are getting the details from the NEWEST StarRatingsReview                                            
    for (Star_Rating_Review__c myRelatedStarRating : [SELECT Id
                                                            ,Account__c
                                                            ,CreatedDate
                                                            ,Review_complete__c
                                                            ,Structure_Type__c
                                                        FROM Star_Rating_Review__c  
                                                       WHERE Review_Complete__c = 'Yes' 
                                                         AND Account__c IN :accountIds 
                                                    order by CreatedDate asc]){
       
      // Ordering by CreatedDate will loop through the Map and put the newest into the Map last, overriding any older values                                                
      accountIdToReviewStructureTypeId.put(myRelatedStarRating.Account__c, myRelatedStarRating.Structure_Type__c);
      accountIdToStarRatingReviewId.put(myRelatedStarRating.Account__c, myRelatedStarRating.Id);
    }  
    
    // Get the accounts for the completed reviews
    List<Account> accounts = [SELECT Id
                                    ,Star_Rating_Structure_Type__c
                                    ,Star_Rating_Review_ID__c
                                FROM Account
                               WHERE Account.Id IN :accountIds];    
  
    
    // Loop through accounts to see if we really need to update the structure type                 
    for (Account account : accounts) {
      // check to see if structure type on review is different than account, or if there is a newer rating review
      if (account.Star_Rating_Structure_Type__c <> accountIdToReviewStructureTypeId.get(account.Id)||
          account.Star_Rating_Review_ID__c <> accountIdToStarRatingReviewId.get(account.Id)){
            
        // structure type is updated so update it on the account
        account.Star_Rating_Structure_Type__c = accountIdToReviewStructureTypeId.get(account.Id);
        account.Star_Rating_Review_ID__c = accountIdToStarRatingReviewId.get(account.Id);
      
        // add account to the list of accounts we want to update
        accountsToUpdate.add(account);  
      }   
    }
    // commit changes to the database
    update accountsToUpdate; 
  }
  
  private Set<Id> accountIds = new Set<Id>();
  private Map<Id,Id> accountIdToReviewStructureTypeId = new Map<Id, Id>();
  private Map<Id,Id> accountIdToStarRatingReviewId = new Map<Id, Id>();  
  private List<Account> accountsToUpdate = new List<Account>();
}