objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <fields>
        <fullName>Super_Region__c</fullName>
        <description>Super region the regions maps to</description>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Super_Region__c.object
<CustomObject>
    <description>Stores the geographical super region where regions are grouped</description>
    <label>Super Region</label>
    <nameField>
        <label>Super Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountClass.cls
public with sharing class AccountClass {

	public void BeforeInsertUpdateAccount(List<Account> accounts) {
		Region__c MEXICO = RegionClass.FindRegionByName('Mexico & Central America');
		Region__c SOUTH_AMERICA = RegionClass.FindRegionByName('South America');
		Super_Region__c SUPER_REGION = SuperRegionClass.FindSuperRegionByName('LATAM');

		for(Account newAcct : accounts) {
			if(newAcct.Region__c == SOUTH_AMERICA.Id || newAcct.Region__c == MEXICO.Id) {
				// set the super region if the region field equals South America or Mexico
				newAcct.Super_Region__c = SUPER_REGION.Id;
			}else if(newAcct.Region__c == NULL && newAcct.Super_Region__c == SUPER_REGION.Id) {
				// clear the super region field if there is no value for region
				newAcct.Super_Region__c = NULL;
			}
		}
	}
}