objects/Assignment_Groups__c.object
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE(User_Active__c &amp; IF(ISPICKVAL(Active__c,&quot;True&quot;)=True,&quot;True&quot;,&quot;False&quot;), 
&quot;TrueTrue&quot;, &quot;/img/samples/light_green.gif&quot;,
&quot;/img/samples/light_red.gif&quot;), 
&quot;status color&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If Status and User Status are True</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002Yj6ZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Out_of_Office_Notice__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date Out of Office Notice will end and case assignment will resume</description>
        <inlineHelpText>The day you will be back in the office</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Out of Office Notice is effective</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Out_of_Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Out of Office Notice</label>
    <nameField>
        <displayFormat>OOF-{00000}</displayFormat>
        <label>Out Of Office Notice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out of Offices Notices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OutOfOfficeNoticeTrigger_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class OutOfOfficeNoticeTrigger_Test {
  static testMethod void myUnitTest() {
  	
    Assignment_Groups__c groupMember = [SELECT User__c
                                          FROM Assignment_Groups__c
                                         LIMIT 1];

    Out_of_Office_Notice__c[] oofNotices = new Out_of_Office_Notice__c[]{new Out_of_Office_Notice__c(User__c = groupMember.User__c, Start_Date__c = System.today(), End_Date__c = System.today()+1),
                                                                       new Out_of_Office_Notice__c(User__c = groupMember.User__c, Start_Date__c = System.today(), End_Date__c = System.today()+1)};
    
    
    insert oofNotices;
    
    oofNotices[0].Status__c = 'Active';
    oofNotices[1].Status__c = 'Inactive';
    
    update oofNotices;
       
  }
}