objects/Assignment_Groups__c.object
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <fields>
        <fullName>Active__c</fullName>
        <description>If True, then include user in Round Robin assignments.</description>
        <inlineHelpText>If False, then include user in Round Robin assignments.</inlineHelpText>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE( 
CASE(User_Active__c &amp; IF(ISPICKVAL(Active__c,&quot;True&quot;)=True,&quot;True&quot;,&quot;False&quot;), 
&quot;TrueTrue&quot;, &quot;/img/samples/light_green.gif&quot;,
&quot;/img/samples/light_red.gif&quot;), 
&quot;status color&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If Status and User Status are True</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002Yj6ZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Out_of_Office_Notice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Out_of_Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Out of Office Notice</label>
    <nameField>
        <displayFormat>OOF-{00000}</displayFormat>
        <label>Out Of Office Notice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out of Offices Notices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OutOfOfficeNoticeClass.cls
public with sharing class OutOfOfficeNoticeClass {
  public void setStatus(Out_of_Office_Notice__c[] oofNotices ){
  	
  	set<Id> oofNoticeUsers = new set<Id>();
  	map<Id,Assignment_Groups__c> UserIdToAssignmentGroup = new map<Id,Assignment_Groups__c>();
  	
    List<Assignment_Groups__c> groupsToUpdate = new List<Assignment_Groups__c>();
  	
  	for(Out_of_Office_Notice__c notice : oofNotices) {
  		oofNoticeUsers.add(notice.User__c);
  	}
  
    Assignment_Groups__c[] groupMembers = [SELECT Id
                                                 ,Active__c
                                                 ,User__c
                                             FROM Assignment_Groups__c
                                             WHERE User__c = :oofNoticeUsers];
                                                
    for(Assignment_Groups__c member : groupMembers) {
      userIdToAssignmentGroup.put(member.User__c,member);
    }
    
    for(Out_of_Office_Notice__c notice : oofNotices) {
    	Assignment_Groups__c thisGroup = userIdToAssignmentGroup.get(notice.User__c);
    	thisGroup.Active__c = notice.Status__c == 'Active' ? 'True' : 'False';
      // NOT DONE IN BULK AS THIS WAS CAUSING APEX ERRORS.  DUPLICATE ID IN LIST
      update thisGroup;
    }
  }
}