objects/Brand__c.object
<CustomObject>
    <description>Brand property rolls into</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>A list to choose Expedia.com (E*), Hotels.com (H*), or both
Added Egencia, Venere and All choices to accommodate UGC.</description>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>E*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Points_of_Sale__c</fullName>
        <label>Points of Sale</label>
        <picklist>
            <picklistValues>
                <fullName>1-Expedia United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Expedia United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Expedia Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6-Expedia Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7-Expedia Voyages-sncf</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8-Expedia Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-Expedia Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11-Expedia Netherlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12-Expedia Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14-Expedia Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15-Expedia Malaysia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16-Expedia South Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17-Expedia Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20-Expedia France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25-Expedia Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26-Hotwire.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27-Expedia India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28-Expedia Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29-Expedia New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60-Expedia Rewards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>63-Expedia Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>64-Expedia Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>65-Expedia Sweden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66-Expedia Norway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>67-Expedia Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>69-Expedia Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70-Expedia Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30001-WWTE United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30003-WWTE Alaska Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30004-WWTE United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

objects/Case_Point_of_Sale__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Points of Sale</relationshipLabel>
        <relationshipName>Case_Points_of_Sale</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Travel_Product__c</fullName>
        <label>Travel Product</label>
        <referenceTo>Travel_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Case_Points_of_Sale</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Point of Sale</label>
    <nameField>
        <displayFormat>CPS{000000}</displayFormat>
        <label>Case Point of Sale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Points of Sale</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Travel_Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Expedia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WWTE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TPID__c</fullName>
        <externalId>true</externalId>
        <label>TPID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Travel Product</label>
    <nameField>
        <label>Travel Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CasePointOfSaleClass.cls
public class CasePointOfSaleClass {
  
  //use this if trigger.isInsert....if it's insert cannot pass trigger.oldmap as it's null
  public void insertCasePointsOfSaleForNewCases(List<Case> myCases){
      List<Case_Point_of_Sale__c> junctionsToInsert = new List<Case_Point_of_Sale__c>();
      List<String> casePicklistPointsOfSale = new List<String>();
      for(Case myCase: myCases){
          string semiColonSeparatedPointsOfSale = myCase.Points_of_Sale__c;
          if (myCase.Points_of_Sale__c != NULL) casePicklistPointsOfSale = semiColonSeparatedPointsOfSale.split(';');
          for (String singlePicklistPointOfSale : casePicklistPointsOfSale){
              Case_Point_of_Sale__c newCasePointOfSale = new Case_Point_of_Sale__c(Case__c = myCase.id, Travel_Product__c = getTravelProductId(singlePicklistPointOfSale));
              // trap incase it couldn't find anything in the map.
              if(newCasePointOfSale.Travel_Product__c != NULL) junctionsToInsert.add(newCasePointOfSale);   
          }
      }
      insert junctionsToInsert;
  } 

  //use this is if trigger.isUpdate. Passses both the trigger.newMap and trigger.oldMap to compare the values
  // Make sure that when the Points of Sale picklist values change, the junction table stays in sync

  public void syncCasePointsOfSale(Map<Id, Case> oldCaseIdtoCaseMap, Map<Id, Case> newCaseIdtoCaseMap){

      List<Case_Point_of_Sale__c> casePointsOfSaleToInsert = new List<Case_Point_of_Sale__c>();
      List<Case_Point_of_Sale__c> casePointsOfSaleToDelete = new List<Case_Point_of_Sale__c>(); 
    
      List<Case_Point_of_Sale__c> currentCasePointsofSaleList =  [SELECT 
                                                                  Id
                                                                  ,Case__c
                                                                  ,Travel_Product__r.Name
                                                                  ,Travel_Product__r.Brand__c
                                                                  ,Travel_Product__r.TPID__c // always need to query, so we can bulid the buildKeyForPicklistValue
                                                                  FROM Case_Point_of_Sale__c 
                                                                  WHERE Case__c IN: newCaseIdtoCaseMap.keyset()];

      for (Case myCase : newCaseIdtoCaseMap.values()){      
          if(newCaseIdtoCaseMap.get(myCase.id).Points_of_Sale__c == oldCaseIdtoCaseMap.get(myCase.id).Points_of_Sale__c){
              system.debug('No changes were made to the Points of Sale for Case: ' + myCase);
          }
          else{
            //build a list of the current Picklist Values
            List<String> currentPointOfSalePicklistValues = new List<String>();
            // because sets MUST be unique, we can compare the Set of New Picklist Values with Old Picklist Values, and use .removeAll() to extract the overlap.
                Set<String> currentPointOfSalePicklistValuesSet = new Set<String>();
                if (myCase.Points_of_Sale__c != NULL) currentPointOfSalePicklistValues = myCase.Points_of_Sale__c.split(';');
                currentPointOfSalePicklistValuesSet.addAll(currentPointOfSalePicklistValues);
                
                //build a unique set of old picklist values
                List<String> oldPointOfSalePicklistValues = new List<String>();
                if (oldCaseIdtoCaseMap.get(myCase.id).Points_of_Sale__c != NULL) oldPointOfSalePicklistValues = oldCaseIdtoCaseMap.get(myCase.id).Points_of_Sale__c.split(';');
                Set<String> oldPointOfSalePicklistValuesSet = new Set<String>();
                oldPointOfSalePicklistValuesSet.addAll(oldPointOfSalePicklistValues);           
                
                //compare sets to insert CasePointOfSales for picklist values that have been added
                Set<String> casePointsOfSaletoAddSet = new Set<String>();
                // Clone the set, so that we don't modify the original
                casePointsOfSaletoAddSet = currentPointOfSalePicklistValuesSet.clone();
                casePointsOfSaletoAddSet.removeAll(oldPointOfSalePicklistValuesSet);
                
                //compare sets to delete CasePointOfSales that have been removed from the picklist
                Set<String> casePointsofSaletoDeleteSet = new Set<String>();
                // Clone the set, so that we don't modify the original
                casePointsofSaletoDeleteSet = oldPointOfSalePicklistValuesSet.clone();
                casePointsofSaletoDeleteSet.removeAll(currentPointOfSalePicklistValuesSet);
                
                //add the new CasePointOfSales records into a list, for mass DML
                for (String newPicklistValue : casePointsOfSaletoAddSet){
                    Case_Point_of_Sale__c newCasePointOfSale = new Case_Point_of_Sale__c(Case__c = myCase.id, Travel_Product__c = getTravelProductId(newPicklistValue));
                    if(newCasePointOfSale.Case__c != NULL && newCasePointOfSale.Travel_Product__c != NULL) casePointsOfSaleToInsert.add(newCasePointOfSale);
                }
                
                //add the CasePointOfSales records we are going to delete into a list, for mass DML
                //is probably a better way of doing this...
                for (String removedPicklistValue : casePointsofSaletoDeleteSet){                
                  for (Case_Point_of_Sale__c casePointofSale : currentCasePointsofSaleList){
                    String primaryKeyforPicklist = buildKeyForPicklistValue(casePointofSale.Travel_Product__r);
                        if (casePointofSale.Case__c == myCase.id && primaryKeyforPicklist == removedPicklistValue){
                            casePointsOfSaleToDelete.add(casePointofSale);                      
                        }
                  }             
                }
          }
      }
      insert casePointsOfSaleToInsert;
      delete casePointsOfSaleToDelete;
  }
  
  //List of all Travel Products in SFDC
  private static List<Travel_Product__c> allTravelProducts = [SELECT 
                                                              Name
                                                             ,Brand__c
                                                             ,TPID__c
                                                             ,Id 
                                                             FROM Travel_Product__c]; 

  //build a unique name from the TravelProduct Name & TPID to be able to map to the picklist value
  // if we change the picklist values, we can just update the code here, and the rest will work
  private static string buildKeyForPicklistValue(Travel_Product__c myTravelProduct){
    return myTravelProduct.TPID__c + '-' + myTravelProduct.Name;  
  }

  //build a map of the TravelProduct key (as defined by the Picklist), to Travel_Product__c Id
  private static Map<String, ID> travelProductKeytoTravelProductIdMap(){
    Map <String, Id> buildingMap = new Map<String, Id> ();
    for (Travel_Product__c  myTravelProduct : allTravelProducts){
      buildingMap.put(buildKeyForPicklistValue(myTravelProduct), myTravelProduct.Id);
    }
    return buildingMap;
  }
  //Get the ID value of the Travel_Product__c using the TravelProduct key (as defined by the Picklist)
  private static Id getTravelProductId(String travelProductKey){
   return travelProductKeytoTravelProductIdMap().get(travelProductKey);
  }  
}