objects/Case.object
<CustomObject>
    <fields>
        <fullName>Involved__c</fullName>
        <label>Involved</label>
        <picklist>
            <picklistValues>
                <fullName>Air CPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CarOps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fare Filing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Fulfillment Process &amp; Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ticketing</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>ADM</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <description>Airline Debit Memos</description>
        <label>ADM</label>
    </recordTypes>
    <recordTypes>
        <fullName>CarOps</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <description>Car Operations</description>
        <label>CarOps</label>
    </recordTypes>
    <recordTypes>
        <fullName>Commissions</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <description>Commissions</description>
        <label>Commissions</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticketing</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <description>Ticketing</description>
        <label>Ticketing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Troubleshooting</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <label>Troubleshooting</label>
    </recordTypes>
</CustomObject>

objects/Case_Process_Team__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Process Teams</relationshipLabel>
        <relationshipName>Case_Process_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <label>Involved</label>
        <picklist>
            <picklistValues>
                <fullName>Yes (Not Owner)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Team__c</fullName>
        <label>Process Team</label>
        <referenceTo>Process_Team__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Case_Process_Teams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ready_to_Close__c</fullName>
        <label>Ready to Close</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Process Team</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Case Process Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Process Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Process_Team__c.object
<CustomObject>
    <label>Process Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/troubleshootingCaseControllerExtension.cls
public class troubleshootingCaseControllerExtension {

    // Built out in the constructor
    public List <Case_Process_Team__c> caseProcessTeams;
    
    // Whether or not the Owner is rendered as an available picklist option
    
    public boolean hasOwner{get;}
    
    public boolean hasOwner(){
    for (Case_Process_Team__c myCaseProcessTeam : caseProcessTeams){    
     if (myCaseProcessTeam.Involved__c == 'Owner') return true;     
    }
        return false;
    }
       
    private final Case finalCase;
    
    public Id getCaseId(){
      return finalCase.id;
    }
    
    public troubleshootingCaseControllerExtension(ApexPages.StandardController controller){
      this.finalCase = (Case)controller.getRecord(); 
      caseProcessTeams = [SELECT Id
                                ,Involved__c
                                ,Process_Team__r.Name
                                ,Additional_Comments__c
                                ,Ready_to_Close__c
                                ,LastModifiedDate
                                ,LastModifiedBy.LastName
                                ,LastModifiedBy.FirstName 
                           FROM Case_Process_Team__c 
                           WHERE Case__c = :getCaseId() 
                           ORDER BY Process_Team__r.Name Asc ];      
    }
        
    // All Options for the Involvement Needed Picklist
  public List<SelectOption> getallOptions(){
    List<SelectOption> all = new List<SelectOption>();
          all.add(new SelectOption('Unknown','Unknown'));
          all.add(new SelectOption('No','No'));
          all.add(new SelectOption('Yes (Not Owner)','Yes (Not Owner)'));
          all.add(new SelectOption('Owner','Owner', false));
    return all;
    }
        
    // All Options, with Owner grayed out if it has already been selected, or selectable if it hasn't already been selected
  public List<SelectOption> getInvolvementList() {
    List<SelectOption> options = new List<SelectOption>();
      options.add(new SelectOption('Unknown','Unknown'));
      options.add(new SelectOption('No','No'));
      options.add(new SelectOption('Yes (Not Owner)','Yes (Not Owner)'));     
      
      if (this.hasOwner() == true){        
      options.add(new SelectOption('Owner','Owner', true));
      return options;
      }    
        // if the owner is NOT the troubleshooting queue, display owner as a NON SELECTABLE field
        else {      
      options.add(new SelectOption('Owner','Owner', false)); 
        return options;
        }
    }
    
    // Yes or No for the Ready to Close field. By manually building it out in the controller we get rid of the "---None---" option.
  public List<SelectOption> getYNList() {
    List<SelectOption> options = new List<SelectOption>();
      options.add(new SelectOption('No','No'));
      options.add(new SelectOption('Yes','Yes'));
    return options;
  	}

  public List<Case_Process_Team__c> getCaseProcessTeams(){
    return caseProcessTeams;
    }
    
    // Go to the Edit Page
    public PageReference editTeams() {
      PageReference nextPage = Page.troubleshootingCaseEditPage;     
      nextPage.setredirect(false);
      return nextPage; 
  }
    
  // Save the InvolvementNeeded Page and return to the Case
  public PageReference saveTeams() {      
    List<Case_Process_Team__c> oldCaseProcessTeams = [SELECT Id
                                                             ,Involved__c
                                                             ,Process_Team__r.Name
                                                             ,Additional_Comments__c
                                                             ,Ready_to_Close__c
                                                         FROM Case_Process_Team__c 
                                                        WHERE Case__c = :finalCase.Id 
                                                     ORDER BY Process_Team__r.Name Asc];
                                                     
      Map<Id, Case_Process_Team__c> oldCaseProcessTeamIdtoCaseProcessTeamMap = new Map<Id, Case_Process_Team__c>();
      
      for (Case_Process_Team__c myOldProcessTeam : oldCaseProcessTeams){
        oldCaseProcessTeamIdtoCaseProcessTeamMap.put(myOldProcessTeam.Id, myOldProcessTeam);
      }
      
      List<Case_Process_Team__c> caseProcessTeamsToUpdate = new List<Case_Process_Team__c>();
      
      for (Case_Process_Team__c currentCaseProcessTeam : caseProcessTeams){
      if (currentCaseProcessTeam.Involved__c == 'No') {
        currentCaseProcessTeam.Ready_to_Close__c = 'Yes';
      }
        if (currentCaseProcessTeam.Involved__c == 'Unknown') {
            currentCaseProcessTeam.Ready_to_Close__c = 'No';            
        }
        Case_Process_Team__c oldCaseProcessTeam = oldCaseProcessTeamIdtoCaseProcessTeamMap.get(currentCaseProcessTeam.Id);
        String newComments = currentCaseProcessTeam.Additional_Comments__c;
        if (newComments == NULL) newComments = '';
        String oldComments = oldCaseProcessTeam.Additional_Comments__c;
        if (oldComments == NULL) oldComments = '';
        //see if anything has changed
        if ((currentCaseProcessTeam.Involved__c != oldCaseProcessTeam.Involved__c) || 
           (currentCaseProcessTeam.Ready_to_Close__c != oldCaseProcessTeam.Ready_to_Close__c) || 
           (newComments != oldComments)){
          caseProcessTeamsToUpdate.add(currentCaseProcessTeam);
        }
      }
      update caseProcessTeamsToUpdate; 
      return reloadPage(false);
  }
     
     // Cancel any of the edits since the last save
  public PageReference cancelTeams() {
    return reloadPage(false);
  }
  
  public PageReference teamPreBooking(){        
    removeUninvolvedTeams(new List<String>{'Ticketing', 'Air Fulfillment Process & Support', 'Regional Team', 'Schedule Change'});
    return reloadPage(false);
  }

     
    //Used for Team Fulfillment button
    public PageReference teamFulfillment() {
    removeUninvolvedTeams(new List<String>{'Air CPR', 'ADM', 'CarOps', 'Commissions', 'Fare Filing', 'Regional Team'});
        return reloadPage(false);
    }
    
    public string getCSSStyle(Case_Process_Team__c myCheckoffJunction){
        if(myCheckoffJunction.Involved__c == 'Yes (Not Owner)' || myCheckoffJunction.Involved__c == 'Owner'){
            return 'workingTeam';
        }
        else{
            return 'nonWorkingTeam';
        }
    }
        
    //incase we want to do anything else when page is refreshsed/updated
    public void UpdateRecords(){
    //getRenderOwner();
    //this.getInvolvementList();   
  }
  
  /**
  
  PRIVATE METHODS
  
  **/
  
  private PageReference reloadPage(boolean setRedirect){
    PageReference nextPage = new PageReference('/'+ getCaseId());
    if (setRedirect == true) nextPage.setredirect(true);
    if (setRedirect == false) nextPage.setredirect(false);
    return nextPage;
  }  

  private void removeUninvolvedTeams(List<String> myUninvolvedTeams){
    string queryWhere = '';
    if (myUninvolvedTeams.size() == 1){
        queryWhere = 'Process_Team__r.Name = \'' + myUninvolvedTeams[0] + '\'';
    }
    if (myUninvolvedTeams.size() > 1){
        Integer teamCount = 1;
        for (String teamName : myUninvolvedTeams){
         queryWhere = queryWhere + 'Process_Team__r.Name = \'' + teamName + '\''; // + '\'OR ';
         if (teamCount < myUninvolvedTeams.size()){
          queryWhere = queryWhere + 'OR ';
         }
         teamCount = teamCount + 1;
      }
    //queryWhere = queryWhere.substring(0,queryWhere.length()-3);
    }
    //Wrapping this in a try/catch method.....better safe than sorry
    try{
        List<Case_Process_Team__c> uninvolvedCheckoffJunctions = Database.query('SELECT Id, Involved__c FROM Case_Process_Team__c WHERE (' + queryWhere + ')AND Case__c = \'' + getCaseId() + '\'');                                                               
      
        for (Case_Process_Team__c myCaseProcessTeam : uninvolvedCheckoffJunctions){
          myCaseProcessTeam.Involved__c = 'No';
          myCaseProcessTeam.Ready_to_Close__c = 'Yes';
        }
        update uninvolvedCheckoffJunctions;
    } catch (Exception e){
        system.debug ('troubleshootingCaseControllerExtension Error: ' + e + 'Case #: ' + getCaseId());
    }
  }
}