objects/Case.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if a case has been allocated to another team</description>
        <inlineHelpText>Used to indicate if a case has been allocated to another team</inlineHelpText>
        <label>Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>Identifies team case is assinged to</description>
        <label>Team</label>
        <picklist>
            <picklistValues>
                <fullName>Air CPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Fulfillment Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airline Debit Memos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Product Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade TSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EID/VID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fare Filing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Partner Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Systems Technical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hothelp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseCloneExtension.cls
public class CaseCloneExtension {

    private final Case parentCase;
    
    public List<String> LanguagesSelected{get;set;} 
    
    public List<Case> RelatedCases {
    	get { return [Select CaseNumber, Team__c, Subject, Priority, CreatedDate, Status, OwnerId From Case Where ParentId = : this.parentCase.Id order by Team__c asc]; }
    }

    public CaseCloneExtension(ApexPages.StandardController controller) {
	  this.parentCase = (Case)controller.getRecord();
	  
	  this.LanguagesSelected = new List<String>();

    }
    
    public Pagereference CloneCases() {
        if(LanguageSelected()) {
            // clone cases
            CaseClass objCase = new CaseClass();
            objCase.assignCaseToLinguist(parentCase, LanguagesSelected);
                
            // update parent status
            this.UpdateParent();
            
            return new Apexpages.StandardController(parentCase).view();
        }else {
                // a language was not selected
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Language: You must enter a value'));
            return Apexpages.currentPage();
        }
    }
    
    public List<SelectOption> getLanguages() {
        List<SelectOption> options = new List<SelectOption>();
        
        // get a list of languages
        for(Language__c item : [Select Id, Name From Language__c order by Name]) {
            options.add(new SelectOption(item.Id, item.Name));
        }
        
        return options;
    }

    ///// Private
    private Boolean LanguageSelected() {
        return LanguagesSelected.isEmpty() == false;
    }
    
    private void UpdateParent() {
    	this.parentCase.Status = 'Assigned to Linguist';
        this.parentCase.Allocated__c = true;
        update this.parentCase;
    }
    
}