objects/Case.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <description>Identifies team case is assinged to</description>
        <label>Team</label>
        <picklist>
            <picklistValues>
                <fullName>Air CPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Fulfillment Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airline Debit Memos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Product Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade TSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EID/VID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fare Filing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Data Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Partner Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Systems Technical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hothelp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <description>Used by internal contacts to set the priority on a case they create via email or web intake form</description>
        <label>Case Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PriorityClass.cls
public with sharing class PriorityClass {
	
	public Map<Id,PriorityClass.Priority> getPriority(List<Case> myCases){
		// query to get related objects
		myCases = [SELECT Id
						 ,Priority
						 ,Type
						 ,Team__c
						 ,Contact.Case_Priority__c
						 ,Account.Rating 
					FROM Case 
				   WHERE Id IN:myCases];
				   
				   
	   // Map<TeamName, Map<CaseType, Priority>>
					   
	   Map<Id,PriorityClass.Priority> casePriorityMap = new Map<Id,PriorityClass.Priority>();
	   
	   for (Case myCase : myCases){
	   		PriorityClass.Priority myPriority = new PriorityClass.Priority();
	   		myPriority.casePriority = myCase.Priority;
	   		myPriority.contactPriority = myCase.Contact.Case_Priority__c;
	   		myPriority.accountPriority = myCase.Account.Rating;	 
	   		casePriorityMap.put(myCase.Id, myPriority);  	
	   }
	   
	   return casePriorityMap;
	}
	
	public Map<Id,PriorityClass.Priority> getPriority(Case myCase){
		List<Case> myCases = new List<Case>{myCase};
		return this.getPriority(myCases);
	}
	
	public class Priority{
		// List<Schema.PicklistEntry> casePriorityValues = Case.Priority.getDescribe().getPicklistValues();
		public string casePriority;
		public string contactPriority;
		public string accountPriority;
		
		public String getHighestPriority(){
			String highestPriority = '';
			return highestPriority;
		}
		/**		
		public Priority(){
							
		}
		**/			
	}
}