objects/Case.object
<CustomObject>
    <fields>
        <fullName>Involved__c</fullName>
        <label>Involved</label>
        <picklist>
            <picklistValues>
                <fullName>Air CPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CarOps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fare Filing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Fulfillment Process &amp; Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ticketing</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Troubleshooting</fullName>
        <active>true</active>
        <businessProcess>Transport</businessProcess>
        <label>Troubleshooting</label>
    </recordTypes>
</CustomObject>

objects/Case_Process_Team__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Process Teams</relationshipLabel>
        <relationshipName>Case_Process_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <label>Involved</label>
        <picklist>
            <picklistValues>
                <fullName>Yes (Not Owner)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Team__c</fullName>
        <label>Process Team</label>
        <referenceTo>Process_Team__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Case_Process_Teams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Process Team</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Case Process Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Process Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Process_Team__c.object
<CustomObject>
    <label>Process Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseProcessTeamClass_Test.cls
/**

DEPENDENCIES

QUEUE
Troubleshooting Transport Queue

RECORD TYPE
Troubleshooting

At least one Process_Team__c in the Database

**/

@isTest
private class CaseProcessTeamClass_Test {

    static testMethod void myUnitTest() {
		CaseProcessTeamClass objCaseProcessTeam = new CaseProcessTeamClass();
    	Map<Id, Case_Process_Team__c> oldMap = new Map<Id, Case_Process_Team__c>();
        Map<Id, Case_Process_Team__c> newMap = new Map<Id, Case_Process_Team__c>();
        List<Case_Process_Team__c> myCaseProcessTeams = new List<Case_Process_Team__c>();
        List<Case_Process_Team__c> updatedCaseProcessTeams = new List<Case_Process_Team__c>();
                
        Process_Team__c myProcessTeam = [SELECT Id FROM Process_Team__c limit 1];
        Case myCase = [SELECT Id FROM Case limit 1];
        Case_Process_Team__c beforeInsert = new Case_Process_Team__c (Case__c = myCase.Id, Process_Team__c = myProcessTeam.Id); 
       
        myCaseProcessTeams.add(beforeInsert);
        objCaseProcessTeam.beforeInsertCaseProcessTeam(myCaseProcessTeams);        
        
        
        insert myCaseProcessTeams;        

        for (Case_Process_Team__c updatedCaseProcessTeam : myCaseProcessTeams){
        	oldMap.put(updatedCaseProcessTeam.Id, updatedCaseProcessTeam);      	
        	updatedCaseProcessTeam.Involved__c = 'No';
        	updatedCaseProcessTeams.add(updatedCaseProcessTeam);
        	newMap.put(updatedCaseProcessTeam.Id, updatedCaseProcessTeam);
        }
        update updatedCaseProcessTeams;            
        objCaseProcessTeam.afterUpdateCaseProcessTeam(newMap, oldMap);
        
        for (Case_Process_Team__c updatedCaseProcessTeam : myCaseProcessTeams){
        	oldMap.put(updatedCaseProcessTeam.Id, updatedCaseProcessTeam);      	
        	updatedCaseProcessTeam.Involved__c = 'Owner';
        	updatedCaseProcessTeams.add(updatedCaseProcessTeam);
        	newMap.put(updatedCaseProcessTeam.Id, updatedCaseProcessTeam);
        }
        objCaseProcessTeam.afterUpdateCaseProcessTeam(newMap, oldMap);

    }
}