objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Last_Interaction__c</fullName>
        <label>Last Interaction</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Enrollment_Chasers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Enrollment Chasers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Mapping_Chasers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Mapping Chasers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Displays the highest rollout step. Can be manually overridden.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Connecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Confirmation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rollout_Step__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Connectivity_Rollouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <referenceTo>Connection__c</referenceTo>
        <relationshipName>Connectivity_Rollouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollout_Step__c</fullName>
        <label>Rollout Step</label>
        <picklist>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Confirmation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rollout Step</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Rollout Step Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollout Steps</pluralLabel>
    <recordTypes>
        <fullName>Connectivity</fullName>
        <active>true</active>
        <label>Connectivity</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RolloutStepClass.cls
public with sharing class RolloutStepClass {
	
	public static List<Rollout_Step__c> getRolloutStepsByConnectionId(Id connectionId){
		return [SELECT Id
                      ,Rollout_Step__c
                      ,OwnerId
                      ,Completed_Date__c
                      ,Case__c
                      ,Owner.Name
                 FROM  Rollout_Step__c
                WHERE  Connection__c = :connectionId
             order by Completed_Date__c asc nulls last];
	}
	
	public static Rollout_Step__c getRolloutStepById(Id rolloutStepId){
		return [SELECT Id
				  FROM Rollout_Step__c
				 WHERE Id = :rolloutStepId];
	}
	
    //Upserting a list touches even unchanged records. This simply pulls out the new steps and inserts them.
    public static void insertNewRolloutSteps(List<Rollout_Step__c> myRolloutSteps){
    	List<Rollout_Step__c> rolloutStepsToInsert = new List<Rollout_Step__c>();
    	for (Rollout_Step__c myRolloutStep : myRolloutSteps){
    		if (myRolloutStep.Id == null){
    			rolloutStepsToInsert.add(myRolloutStep);
    		}
    	}
    	if (rolloutStepsToInsert.size() > 0) insert rolloutStepsToInsert;    	
    }
    
    //Syncronize the Number of Chaser Fields & Connection Status on the Connection Object for HSTS Connectivity
    public static void updateConnection(List<Rollout_Step__c> myRolloutSteps){
    	Map<Id, String> connectionStatusMap = new Map<Id, String>();
	    Map<Id, Integer> mappingChasers = new Map<Id, Integer>();
	    Map<Id, Integer> enrollmentChasers = new Map<Id, Integer>();
	    
	    RecordType connectivityRolloutStepRecordType = [SELECT Id 
                                                   		  FROM RecordType 
                                                  		 WHERE sObjectType = 'Rollout_Step__c' 
                                                    	   AND DeveloperName = 'Connectivity'];
	    
	    for (Rollout_Step__c rolloutStep : myRolloutSteps){	    	
	    	if (rolloutStep.RecordTypeId == connectivityRolloutStepRecordType.Id){	    	
		        connectionStatusMap.put(rolloutStep.Connection__c, rolloutStep.Rollout_Step__c);
		        
		        if(rolloutStep.Rollout_Step__c.contains('Mapping Chaser')){
		        	if (mappingChasers.containsKey(rolloutStep.Connection__c)){
		        		mappingChasers.put(rolloutStep.Connection__c, mappingChasers.get(rolloutStep.Connection__c) + 1);
		        	} else{		        	
		            mappingChasers.put(rolloutStep.Connection__c, 1);
		        	}
		        }
		        if(rolloutStep.Rollout_Step__c.contains('Enrollment Chaser')){
		        	if (enrollmentChasers.containsKey(rolloutStep.Connection__c)){
		        		enrollmentChasers.put(rolloutStep.Connection__c, enrollmentChasers.get(rolloutStep.Connection__c) + 1);
		        	} else{	
		            enrollmentChasers.put(rolloutStep.Connection__c, 1);
		        	}
		        }
	    	}
	    }
	
	    List<Connection__c> myConnections = [SELECT Id
	                                               ,Status__c
	                                               ,Number_of_Enrollment_Chasers__c
	                                               ,Number_of_Mapping_Chasers__c 
	                                           FROM Connection__c 
	                                          WHERE Id In :connectionStatusMap.keySet()];
	    
	    for (Connection__c myConnection : myConnections){
	        myConnection.Status__c = connectionStatusMap.get(myConnection.Id);
	        if (enrollmentChasers.containsKey(myConnection.Id)){
	            myConnection.Number_of_Enrollment_Chasers__c = myConnection.Number_of_Enrollment_Chasers__c + enrollmentChasers.get(myConnection.Id);
	            myConnection.Last_Interaction__c = system.now();
	        }  
	        if (mappingChasers.containsKey(myConnection.Id)){
	            myConnection.Number_of_Mapping_Chasers__c = myConnection.Number_of_Mapping_Chasers__c + mappingChasers.get(myConnection.Id);
	            myConnection.Last_Interaction__c = system.now();
	        }
	        if (myConnection.Status__c == 'Enrollment Form Sent' || myConnection.Status__c == 'Mapping Information Sent' ){
	            myConnection.Last_Interaction__c = system.now();
	        }  
	    }
	    update myConnections;
    }

}