objects/Connectivity_System__c.object
<CustomObject>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Connectivity_System_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connectivity System Contacts</relationshipLabel>
        <relationshipName>Connectivity_System_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connectivity System Contacts</relationshipLabel>
        <relationshipName>Connectivity_System_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Connectivity System Contact</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Connectivity System Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connectivity System Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

classes/ConnectivitySystemContactClass_Test.cls
@isTest
private class ConnectivitySystemContactClass_Test {

    static testMethod void myUnitTest() {
    	Connectivity_System__c myConnectivitySystem = new Connectivity_System__c (Name = 'TestConnectivitySystem');
    	insert myConnectivitySystem;
    	
    	Contact myContact = new Contact (LastName = 'Test');
    	insert myContact;
    	
    	Connectivity_System_Contact__c myConnectivitySystemContact = new Connectivity_System_Contact__c(Connectivity_System__c = myConnectivitySystem.Id, Contact__c = myContact.Id);
    	insert myConnectivitySystemContact;
    	
		List<Connectivity_System_Contact__c> myConnectivitySystemContacts = ConnectivitySystemContactClass.findByConnectivitySystemId(myConnectivitySystem.Id);        
		system.assertEquals(myConnectivitySystemContacts.size(), 1);
    }
}