objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_Checklist_Created_By__c</fullName>
        <description>Lookup to User that created checklist in PSG Salesforce</description>
        <label>PSG Checklist Created By</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract_Loading_Step__c.object
<CustomObject>
    <description>Status in Contract Loading related to Contract Checklist for History Tracking purposes</description>
    <fields>
        <fullName>Contract_Checklist__c</fullName>
        <label>Contract Checklist</label>
        <referenceTo>Contract_Checklist__c</referenceTo>
        <relationshipLabel>Contract Loading Steps</relationshipLabel>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract_Loading_Step__c</fullName>
        <label>Contract Loading Step</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSG_User_Role_Name__c</fullName>
        <label>PSG User Role Number Assigned To</label>
        <referenceTo>PSG_User_Role__c</referenceTo>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User_Role__c</fullName>
        <formula>TEXT(PSG_User_Role_Name__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSG User Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <description>Lookup to PSG User object for assigning Step to user in PSG Org</description>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Loading Steps</relationshipLabel>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Loading Step</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Loading Steps Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Loading Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PSG User Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractLoadingStepAccountTeamExtension.cls
public with sharing class ContractLoadingStepAccountTeamExtension {
	private Contract_Loading_Step__c step;
	private Contract_Checklist__c checklist;
	public List<PSG_User_Role__c> memberList {get;set;}
	public List<PSG_User__c> creatorList {get;set;}
 	public Contract_Loading_Step__c myContractLoadingStep {get;set;}
	
	private ContractLoadingStepClass objContractLoadingStep = new ContractLoadingStepClass();
	private ContractChecklistClass objContractChecklist = new ContractChecklistClass();
	
  public ContractLoadingStepAccountTeamExtension(ApexPages.StandardController controller) {
    step = (Contract_Loading_Step__c)controller.getRecord();
    
    // get a handled on the step with all the fields needed for the page
    step = ContractLoadingStepClass.findById(step.Id);
    // get a copy for the section of the page that will rerender
    myContractLoadingStep = step;
    
    //get the checklist this step rolls up to  
    checklist = ContractChecklistClass.findById(step.Contract_Checklist__c);
                   
  }
  
  public Id getAccountId() {
  	if(checklist == null) {
  	  checklist = ContractChecklistClass.findById(step.Contract_Checklist__c);	
  	}
  	return checklist.Account__c;
  }
  
  public List<PSG_User_Role__c> getAccountTeamMembers() {
  	if(memberList == null) {
    	memberList = PSGUserRoleClass.findByAccount(checklist.Account__c);  
  	}
  	return memberList;   
  }
  
  public List<PSG_User__c> getChecklistCreators() {
  	if(creatorList == null) {
  		Set<Id> creatorIds = new Set<Id>();
  		creatorIds.add(checklist.PSG_Checklist_Created_By__c);
  		creatorList = PSGUserClass.findAllByPSGIds(creatorIds);
  	}
  	return creatorList;
  }
  
  public pageReference userRole() {
  	
    //PSG_User_Role__c userRole = PSGUserRoleClass.findByName(ApexPages.currentPage().getParameters().get('roleNumber'));                                  
    PSG_User__c psgUser = PSGUserClass.findById(ApexPages.currentPage().getParameters().get('psgUser'));
                                  
    //myContractLoadingStep.PSG_User_Role_Name__c = userRole.Id;
    myContractLoadingStep.PSG_User__c = psgUser.Id;
    
    update myContractLoadingStep;
    
    myContractLoadingStep = ContractLoadingStepClass.findById(myContractLoadingStep.Id);
    
    return null;
  }
}