objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_Checklist_Created_By__c</fullName>
        <description>Lookup to User that created checklist in PSG Salesforce</description>
        <label>PSG Checklist Created By</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractChecklistClass.cls
public with sharing class ContractChecklistClass {
	
	public static Contract_Checklist__c findById(Id contractChecklistId) {
		
		return [SELECT Id
                  ,Account__c
                  ,Status__c
                  ,PSG_Checklist_Created_By__c
              FROM Contract_Checklist__c
             WHERE Id = :contractChecklistId
             LIMIT 1];
	}
	
	public static List<Contract_Checklist__c> findByIds(Set<Id> checklistIds) {
	  return [SELECT Id
	                ,Account__c
                  ,Status__c
              FROM Contract_Checklist__c
             WHERE Id IN :checklistIds];	
	}
    
  public void statusChanged(List<Contract_Checklist__c> changedStatuses){
    ContractLoadingStepClass objStep = new ContractLoadingStepClass();
    objStep.newContractLoadingSteps(changedStatuses);
  }
    
  public void updateContractChecklistStatus(Set<Id> checklistIds,String status) {
        
    List<Contract_Checklist__c> checklists = ContractChecklistClass.findByIds(checklistIds);
                                                  
    for(Contract_Checklist__c checklist : checklists) {
      checklist.Status__c = status;
    }
        
    update checklists;
  }
}