objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HS_Audit_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for mass emailing contacts where the HS Audit is pending or Not Started</description>
        <label>HS Audit Pending</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Health_Safety_Audit__c.object
<CustomObject>
    <description>Health and Safety Custom Object to capture information specific to Health and Safety Cases</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Health_Safety</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Audit_Status__c</fullName>
        <label>Audit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Admin Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Audit__c</fullName>
        <label>Audit</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Health &amp; Safety Audits</relationshipLabel>
        <relationshipName>Health_Safety_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Health &amp; Safety Audit</label>
    <nameField>
        <displayFormat>HS-{00000}</displayFormat>
        <label>Health &amp; Safety Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health &amp; Safety Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HealthSafetyAuditClass.cls
public with sharing class HealthSafetyAuditClass {

	public void SetHSAuditPending(List<Health_Safety_Audit__c> hsAudits) {
		List<Contact> lstContacts = new List<Contact>();
		
		// compile list of contact Ids
		List<Id> contactIds = new List<Id>();
		for(Health_Safety_Audit__c item : hsAudits) {
			if(item.Contact__c != null) {
				contactIds.add(item.Contact__c);
			}
		}
		
		// get list of contacts with associated health and safety audits that are pending or not started
		for(Contact c : [Select (Select Id, Name, RecordTypeId, Account__c, Audit_Status__c, Audit__c, IsDeleted From Health_Safety_Audits__r Where Audit__c = 'Self Assessment' and (Audit_Status__c = 'Pending' or Audit_Status__c = 'Not Started') and IsDeleted = false) From Contact c Where Id IN : contactIds]) {
			c.HS_Audit_Pending__c = (c.Health_Safety_Audits__r.isEmpty() == false);
			lstContacts.add(c);
		}
		
		update lstContacts;
	}
}