objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PSG User Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractChecklistAccountTeamExtension.cls
public with sharing class ContractChecklistAccountTeamExtension {
	public List<PSG_User_Role__c> memberList {get;set;}
	private Contract_Checklist__c checklist;
	
	public ContractChecklistAccountTeamExtension(ApexPages.StandardController controller) {
		checklist = (Contract_Checklist__c)controller.getRecord();
		
		checklist = ContractChecklistClass.findById(checklist.Id);	
	}
	
	public Id getAccountId() {
    return checklist.Account__c;
	}
	
	 public List<PSG_User_Role__c> getAccountTeamMembers() {
    if(memberList == null) {
      memberList = PSGUserRoleClass.findByAccount(checklist.Account__c);       
    }
    return memberList;   
  }

}