objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>PSG_Checklist_Created_By__c</fullName>
        <description>Lookup to User that created checklist in PSG Salesforce</description>
        <label>PSG Checklist Created By</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract_Loading_Step__c.object
<CustomObject>
    <description>Status in Contract Loading related to Contract Checklist for History Tracking purposes</description>
    <fields>
        <fullName>Contract_Checklist__c</fullName>
        <label>Contract Checklist</label>
        <referenceTo>Contract_Checklist__c</referenceTo>
        <relationshipLabel>Contract Loading Steps</relationshipLabel>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract_Loading_Step__c</fullName>
        <label>Contract Loading Step</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PSG_User_Name__c</fullName>
        <formula>PSG_User_Role_Name__r.PSG_User__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSG User Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSG_User_Role_Name__c</fullName>
        <label>PSG User Role Number Assigned To</label>
        <referenceTo>PSG_User_Role__c</referenceTo>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User_Role__c</fullName>
        <formula>TEXT(PSG_User_Role_Name__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSG User Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <description>Lookup to PSG User object for assigning Step to user in PSG Org</description>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Loading Steps</relationshipLabel>
        <relationshipName>Contract_Loading_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Loading Step</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Loading Steps Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Loading Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PSG User Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractLoadingStepClass.cls
public with sharing class ContractLoadingStepClass {
	
	public static Contract_Loading_Step__c findById(Id contractLoadingStepId) {
		
		return [SELECT Id
                  ,Contract_Checklist__c
                  ,PSG_User__c
                  ,PSG_User_Name__c
                  ,PSG_User_Role_Name__c
                  ,PSG_User_Role__c
              FROM Contract_Loading_Step__c
             WHERE Id = :contractLoadingStepId
             LIMIT 1];
	}
	
	public void newContractLoadingSteps(List<Contract_Checklist__c> checklists) {
		Map<String,Id> userRoleIdByAccountPSGUserMap = new Map<String,Id>();
		Set<Id> checklistIds = new Set<Id>();
		Set<Id> creatorIds = new Set<Id>();
		
		for(Contract_Checklist__c checklist : checklists) {
			checklistIds.add(checklist.Id);
			creatorIds.add(checklist.PSG_Checklist_Created_By__c);
		}
		List<Contract_Loading_Step__c> newSteps = new List<Contract_Loading_Step__c>();
    List<Contract_Loading_Step__c> stepsNotComplete = completeOutstandingContractLoadingStepsByContractChecklistId(checklistIds);
		for(Contract_Checklist__c checklist : checklists) {
			
		  //Contract_Loading_Step__c newStep = newContractLoadingStep(checklist.status__c, checklist.Id, this.contractReturnedToMM(checklist.Status__c) ? checklist.PSG_Checklist_Created_By__c : null);
		  Contract_Loading_Step__c newStep = newContractLoadingStep(checklist.status__c, checklist.Id, null);
		  
		  if(newStep != null) {
  		  newSteps.add(newStep);
		  } 
		}
		
		system.debug('newSteps.size()=' + newSteps.size());
		if(newSteps.size() > 0) {
			system.debug('BEFORE insert');
			insert newSteps;
		}
		
		if(stepsNotComplete.size() > 0) {
			update stepsNotComplete;
		}	
	}
	
	public List<Contract_Loading_Step__c> completeOutstandingContractLoadingStepsByContractChecklistId(Set<Id> contractChecklists) {
		List<Contract_Loading_Step__c> stepsNotComplete = [SELECT Id
		                                                         ,Contract_Checklist__c
		                                                         ,Status__c
		                                                     FROM Contract_Loading_Step__c
		                                                    WHERE Status__c <> 'Complete'
		                                                      AND Contract_Checklist__c IN :contractChecklists
		                                                    ORDER By Contract_Checklist__c];
		                                                    
	  for(Contract_Loading_Step__c step : stepsNotComplete) {
	    step.Status__c = 'Complete'; 	
	  }
		return stepsNotComplete;
	}
	
	public void marketManagerTaskComplete(List<Contract_Loading_Step__c> steps) {
		
		Set<Id> checklistIds = new Set<Id>();
		
		for(Contract_Loading_Step__c step : steps) {
			if(step.Contract_Loading_Step__c == 'Contract Returned to MM/MC-See Comments'
			  && step.Status__c == 'Completed') {
			  checklistIds.add(step.Contract_Checklist__c);
		  }
		}
		ContractChecklistClass objChecklist = new ContractChecklistClass();
	  objChecklist.updateContractChecklistStatus(checklistIds, 'Contract Returned to Loading Team');
		
	}
	
	private Contract_Loading_Step__c newContractLoadingStep(String checklistStatus, Id checklist, Id psgUser) {
		
		Contract_Loading_Step__c newStep;
		System.debug('NEW-CONTRACT-LOADINGSTEP-STATUS=' + checklistStatus);
		
		newStep = new Contract_Loading_Step__c(Status__c = 'Open'
                                          ,Contract_Loading_Step__c = checklistStatus
		                                      ,Contract_Checklist__c = checklist
		                                      ,PSG_User__c = psgUser);
	
		return newStep;
	}
	
	private Boolean contractReturnedToMM(String status) {
		return status == 'Contract Returned to MM/MC-See Comments';
	}
	
	
}