objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if user is active is PSG Salesforce</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PSGUserClass.cls
public with sharing class PSGUserClass {
	
	public static List<PSG_User__c> findAllByPSGIds(Set<Id> Ids) {
		return [SELECT Id
		              ,Name
		              ,Active__c
		              ,Email__c
		              ,Phone__c
		              ,Title__c
		          FROM PSG_User__c
		         WHERE Id IN :Ids];
	}	
	
	public static PSG_User__c findById(Id psgUserId) {
		return [SELECT Id
                  ,Name
                  ,Active__c
                  ,Email__c
                  ,Phone__c
                  ,Title__c
              FROM PSG_User__c
             WHERE Id = :PsgUserId];
  } 
	
	private static PSG_User__c findUser(String whereClause) {
		
		String soql = 'SELECT Id ' +
                  ',Name ' +
                  ',Active__c ' +
                  ',Email__c ' +
                  ',Phone__c ' +
                  ',Title__c ' +
              'FROM PSG_User__c ' +
              'WHERE ' + whereClause +
              'LIMIT 1';
     
    PSG_User__c user = Database.query(soql);
    return user;
	}

}