objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PSGUserClass_Test.cls
@isTest
private class PSGUserClass_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        PSG_User__c psgUser = new PSG_User__c();
        
        psgUser.Email__c = 'test@test.com';
        psgUser.Name = 'Joe User';
        
        insert psgUser;
        
        PSG_User__c foundPSGUser = PSGUserClass.findById(psgUser.Id);
        
        system.assertEquals(psgUser.Id,foundPSGUser.Id);
        
    }
}