objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Market Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line Managers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PSG User Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PSGUserRoleClass.cls
public with sharing class PSGUserRoleClass {
	
	public static List<PSG_User_Role__c> findByAccount(Id accountId) {
		return [SELECT Id
                  ,Name
                  ,Role__c
                  ,Account__c
                  ,Account__r.Name
                  ,PSG_User__c
                  ,PSG_User__r.Name
                  ,PSG_User__r.Phone__c
                  ,PSG_User__r.Email__c
              FROM PSG_User_Role__c
             WHERE Account__c = :accountId
             ORDER BY Role__c ASC];
	}
	
	public static PSG_User_Role__c findByName(String psgUserRoleName) {
	  return [SELECT Id
                  ,Name
                  ,Role__c
                  ,Account__c
                  ,Account__r.Name
                  ,PSG_User__c
                  ,PSG_User__r.Name
                  ,PSG_User__r.Phone__c
                  ,PSG_User__r.Email__c
              FROM PSG_User_Role__c
             WHERE Name = :psgUserRoleName
             LIMIT 1];	
	}
	


}