objects/Star_Rating_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Star_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_complete__c</fullName>
        <label>Review completed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Structure_Type__c</fullName>
        <label>Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Star Rating Reviews</relationshipLabel>
        <relationshipName>Star_Rating_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Star Rating Review</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Star Ratings Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Star Rating Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Structure_Type__c.object
<CustomObject>
    <description>The structure types that a property can be classified as.</description>
    <label>Structure Type</label>
    <nameField>
        <label>Structure Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Structure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StarRatingReviewTrigger_Test.cls
@isTest
private class StarRatingReviewTrigger_Test {

    static testMethod void myUnitTest() {
      Account testAccount = new Account (Name = 'TestAccount');
      insert testAccount;
   
      Structure_Type__c testStructure = new Structure_Type__c (Name = 'TestStructure');
      insert testStructure;
      
      Star_Rating_Review__c testStarRating = new Star_Rating_Review__c (Account__c  = testAccount.Id, Structure_Type__c = testStructure.Id, Review_Complete__c = 'Yes');        
      insert testStarRating;
    }
}